# Configuration for pack monte carlo simulations
defaults:
  logger_level: &LOG_LEVEL ERROR

models:
  - class: qOCV_Differential
    module: src.models.submodels.ocv
    kwargs:
      logger_level: *LOG_LEVEL
      alpha: 0.5
  - class: Plett_Hysteresis
    module: src.models.submodels.hysteresis
    kwargs:
      logger_level: *LOG_LEVEL
      g: 0.005


simulation:
  temperatures: [15, 25, 35, 45]

  samples: 200

  mode: 'thevenin'

  paths:
    parameters:
      dist_folder: "../data/distributions"
      file_naming_scheme: "{temp}deg.parquet"
      param_labels: ['mu_R0', 'sigma_R0', 'mu_tau1_inv', 'sigma_tau1_inv',
                    'mu_c1_inv', 'sigma_c1_inv', 'mu_tau2_inv', 'sigma_tau2_inv',
                    'mu_c2_inv', 'sigma_c2_inv']
    ocv:
      ocv_folder: "../data/measurements/qocv20"
